### ISSUE TITLE
After upgrading rspamd to 1.7.9 haraka with rspamd plugin crashes

### ISSUE THREAD

**Issue by pvagner** [haraka/haraka-plugin-rspamd#11]
### system info

Haraka | Haraka.js — Version: 2.8.21
 --- | :--- 
Node | v10.8.0
OS | Linux vps.pvagner.tk 3.16.6-042stab127.46 #1 SMP Wed Mar 28 01:57:40 CEST 2018 x86_64 GNU/Linux
openssl | OpenSSL 1.1.0h  27 Mar 2018

### Expected behavior

I'd like to check incoming emails via rspamd plugin. Most likelly this is a change in rspamd that this plugin should be able to get into account however I am unable to figure it out.
Previously I was running rspamd 1.7.1 and I have updated to rspamd 1.7.9 skipping minor updates that were released in between.

### Observed behavior

Haraka gets the email, calls all the hooks, rspamd processes the messages but causes haraka to act on an undefined variable I guess.

```
[DEBUG] [28745188-9D90-4CC8-B4D4-3F39C7DE38C0.1] [core] running data_post hook in rspamd plugin
[DEBUG] [-] [core] addOCSP: not available
[NOTICE] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] connect ip=<ipv4AddressHere> port=43914 local_ip=<ipv4AddressHere> local_port=25
[DEBUG] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] running connect_init hooks
[DEBUG] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] running connect_init hook in early_talker plugin
[INFO] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] client [<ipv4AddressHere>] half closed connection
[DEBUG] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] client has disconnected
[DEBUG] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] running disconnect hooks
[DEBUG] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] client has disconnected
[DEBUG] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] running disconnect hook in tls plugin
[DEBUG] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] client has disconnected
[DEBUG] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core]  hook=disconnect plugin=tls function=hook_disconnect params="" retval=CONT msg=""
[NOTICE] [599041A5-D3FA-4C8E-B9C3-4558A2AAEC56] [core] disconnect ip=<ipv4AddressHere> rdns="" helo="" relay=N early=N esmtp=N tls=N pipe=N errors=0 txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="" time=5.003
[INFO] [28745188-9D90-4CC8-B4D4-3F39C7DE38C0.1] [rspamd] action: no action, is_skipped: false, required_score: 15, score: -2.896589, time: 5.13
[CRIT] [-] [core] TypeError: value.replace is not a function
[CRIT] [-] [core]     at Header.add_end (/usr/lib/node_modules/Haraka/mailheader.js:164:23)
[CRIT] [-] [core]     at Transaction.add_header (/usr/lib/node_modules/Haraka/transaction.js:154:21)
[CRIT] [-] [core]     at Object.keys.forEach (/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-rspamd/index.js:181:36)
[CRIT] [-] [core]     at Array.forEach (<anonymous>)
[CRIT] [-] [core]     at Plugin.exports.do_milter_headers (/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-rspamd/index.js:180:46)
[CRIT] [-] [core]     at IncomingMessage.res.on (/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-rspamd/index.js:240:24)
[CRIT] [-] [core]     at IncomingMessage.emit (events.js:187:15)
[CRIT] [-] [core]     at endReadableNT (_stream_readable.js:1081:12)
[CRIT] [-] [core]     at process._tickCallback (internal/process/next_tick.js:63:19)
[NOTICE] [-] [core] Shutting down
```

### Steps to reproduce
```
# config/plugins
early_talker
helo.checks
tls
ldap
mail_from.is_resolvable
bounce
data.headers
attachment
queue/lmtp
limit

# config/rspamd.ini
add_headers=always

[check]
authenticated=true
private_ip=true

[reject]
authenticated=true

[dkim]
enabled=false
```

And then make sure incoming email kicks in.

**Comment by pvagner** [comment]
As per the trace back above the line 181 of haraka-plugin-rspamd/index.js reads like this:
```
            connection.transaction.add_header(key, data.milter.add_headers[key]);
```
I have changed it to
```
            connection.transaction.add_header(key, data.milter.add_headers[key].value);
```
And it appears to work again.
However I can't verify if this has been changed in rspamd or what.
The failing code also deals with header.value and I am not sure if it's looking at this same object or if it's something internal to haraka.
Thus I have no pull request... nothing because this is just a bit of trial and error on my part for the time being.
I would appreciate if you can look into this and give me a hint so I can better understand why this might have happened or appreciate the proper fix it-self.

Greetings

Peter

**Comment by msimerson** [comment]
> And it appears to work again.

Since I'm not sure what "appears to work" means, does it add the milter headers after appending the `.value` to the line?  I don't have this issue (with rspamd 1.8.0 or 1.8.1) but another useful thing to test would be logging `data.milter.add_headers[key]` and see exactly what it is. If your getting a null in there (or something like that) the solution might look more like this:

```js
~/git/haraka-plugin-rspamd $ git diff
diff --git a/index.js b/index.js
index 3a25328..fd2dc1e 100644
--- a/index.js
+++ b/index.js
@@ -179,7 +179,9 @@ exports.do_milter_headers = function (connection, data) {
 
     if (data.milter.add_headers) {
         Object.keys(data.milter.add_headers).forEach((key) => {
-            connection.transaction.add_header(key, data.milter.add_headers[key]);
+            const header_value = data.milter.add_headers[key];
+            if (!header_value) return;
+            connection.transaction.add_header(key, header_value);
         })
     }
 }
```

**Comment by PHPGangsta** [comment]
The problem seems to be the "Authentication-Results" header, which is an object:

```
[INFO] [39AD0C20-9EA0-43B2-8AA6-90375405763A.1] [rspamd] add_header: X-Spamd-Bar ++++ string
[INFO] [39AD0C20-9EA0-43B2-8AA6-90375405763A.1] [rspamd] add_header: X-Spam-Level **** string
[INFO] [39AD0C20-9EA0-43B2-8AA6-90375405763A.1] [rspamd] add_header: X-Rspamd-Server testmaschine01 string
[INFO] [39AD0C20-9EA0-43B2-8AA6-90375405763A.1] [rspamd] add_header: Authentication-Results [object Object] object
[CRIT] [-] [core] TypeError: value.replace is not a function
[CRIT] [-] [core]     at Header.add_end (/usr/local/lib/node_modules/Haraka/mailheader.js:164:23)
[CRIT] [-] [core]     at Transaction.add_header (/usr/local/lib/node_modules/Haraka/transaction.js:154:21)
[CRIT] [-] [core]     at Object.keys.forEach (/usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-rspamd/index.js:187:36)
[CRIT] [-] [core]     at Array.forEach (<anonymous>)
[CRIT] [-] [core]     at Plugin.exports.do_milter_headers (/usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-rspamd/index.js:182:46)
[CRIT] [-] [core]     at IncomingMessage.res.on (/usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-rspamd/index.js:246:24)
[CRIT] [-] [core]     at emitNone (events.js:111:20)
[CRIT] [-] [core]     at IncomingMessage.emit (events.js:208:7)
[CRIT] [-] [core]     at endReadableNT (_stream_readable.js:1064:12)
[CRIT] [-] [core]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

The following code is working fine here, it's a mixture of your solutions: 
- Check for NULL/empty values, and 
- if it's an object: use the "value" property

```javascript
const header_value = data.milter.add_headers[key];
if (!header_value) return;

if (typeof header_value === 'object') {
    connection.transaction.add_header(key, header_value.value);
} else {
    connection.transaction.add_header(key, header_value);
}
```

Now I see all rspamd headers in the mail:
```
X-Spamd-Bar: ++++
X-Spam-Level: ****
X-Rspamd-Server: testmaschine01
Authentication-Results: testmaschine01;
	dmarc=fail reason="" header.from=XXXX.de (policy=none);
	spf=softfail (testmaschine01: 1.2.3.4 is neither permitted nor denied by domain of mk@XXXX.de) smtp.mailfrom=mk@XXXX.de
X-Rspamd-Queue-Id: 800EBEAA-1486-42F6-AEEF-85227E769520.1
X-Spamd-Result: default: False [4.47 / 10.00];
	 ARC_NA(0.00)[];
     ...
```
